M48
; DRILL file {KiCad 9.0.7} date 2026-04-18T16:59:34+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-18T16:59:34+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X114.5Y-72.6
X236.3Y-72.6
T2
X111.75Y-64.8
X164.2Y-64.8
X239.05Y-64.8
M30
